### PR TITLE
90% finished quiz

### PR DESCRIPTION
**Pull request by jkillz2020**
maths suck

### CODE REVIEW

**Comment by zoeames** [comment]
you have some really strange git stuff happening here.  At the root of this project you have a readme and a quizzes folder.  inside that quizzes folder you have a static-web folder.  inside that static-web folder you have a javascript folder.  inside that javascript folder you have index.html and quiz.js.  Why so many folders?  Fix your structure.  You should have at the root 3 files - readme.md, quiz.js, and index.html - there should be no folders.  Once you fix this problem (or come see me and we can do it together) slack me and I will then look at your code

**Comment by jkillz2020** [comment]
well…..crap

**Comment by jkillz2020** [comment]
ok I got the quiz working...again....there were some ID differences and on mine the functions for building tree were nested inside the math function so it wasn't working.  It is console logging now and I have commented the code.

Thanks

**Comment by zoeames** [comment]
Hey i don't actually see working code.  when i enter values into the input it prints a single row.  go back and check your code to make sure you pushed up everything you think you need.  If you are still having trouble wednesday lets sit down together and go through it.

**Comment by jkillz2020** [comment]
I just forgot to commit the latest....should be there now!

**Comment by zoeames** [comment]
just need to get the key press working and then you are perfect!

**Comment by zoeames** [comment]
ahhh i see what you did.  using form submit.  While this technically does work what would you do if i asked you to get the tree to build when i press the B key instead of the enter key?   Using the form submit won't work in this case.   Give it another try you are so close. Hint:  uncomment out line 57 and change it to:
buildButton.addEventListener("keypress", enterFunction);
Then you will need to write an function called enterFunction where you add in the logic for pressing enter - 2nd hit google keyCode = 13

**Comment by jkillz2020** [comment]
change it to???

**Comment by zoeames** [comment]
:+1:

**Pull request merged**
